### ISSUE TITLE
open files with no extension

### ISSUE THREAD

**Issue by retrotails** [ArturKovacs/emulsion#137]
recently emulsion gained support for opening images with the incorrect extension, say image.png which is actually jpg, but it cannot open files with either no extension or an extension that isn't normally used to name an image. I ran into this when using https://github.com/tulir/gomuks as files it saves are a random string of text with no extension.

**Comment by ArturKovacs** [comment]
The reason why emulsion checks for the extension is that when you open a folder with a bunch of non-image files you want emulsion to silently skip those. This check has to be done for every file in the folder when the folder is opened in order to display the slider at the bottom correctly (because only image files are considered a step for the slider).

A much more robust way of doing this check would be to read the first few bytes of each file in the folder in order to deremine the type regardless of the extension. I'm guessing this would be significantly slower however. The -I guess- diligent thing to do would be to measure how slow that would be on each platform and depending on the result it could either

- simply read into the files instead of just checking the extension
- read into the files on a parallel thread
- stay with the extension check and adding a mode for attempting to load all files regardless of their extension. Here the mode switch could be triggered with a key, be a config field, or be a command line option or some combination of those.

Or we just say meh, skip the measurement and go with the third option.

**Comment by retrotails** [comment]
from what I've tested in other image viewers, they all seem to correctly populate all the images in the folder regardless of extension. maybe you could find what the longest string of bytes is you need to distinguish between all supported files, and read only that many bytes from each file.
personally I'm actually slightly surprised most viewers don't care about extension at all, I think acceptable behavior would be; use only file extensions for browsing through a folder, but try to open any image if it's explicitly opened from the commandline.

**Comment by paolobarbolini** [comment]
> maybe you could find what the longest string of bytes is you need to distinguish between all supported files, and read only that many bytes from each file

That's totally possible. You can infer the file type simply by looking at the file magic bytes.
There's a crate dedicated to it [infer crate](https://docs.rs/infer/0.2.3/infer/image/index.html) and it's also what happens when you call [image::guess_format](https://docs.rs/image/0.23.8/src/image/io/free_functions.rs.html#258-290)

**Comment by ArturKovacs** [comment]
I ran a test on a folder with 757 files, 378 of which are png images. Reading the first 512 bytes and using `image::guess_format` on every file it takes around 100 ms in release mode to load the folder. Or to be more prceise, after loading the same folder 44 times, the results are the following.
```
avg 103 ms
min 69 ms
max 138 ms
```

I did this on Windows and I collected these number after having the test ran prior. This means that the files were probably already cached when I did the measurement. I'll repeat this test on Linux shortly and I'll try to include the time of the very first load.

**Comment by ArturKovacs** [comment]
The results are very similar on Linux but just for the curious, here are the results I got with kernel `5.4.0-47-generic`
```
avg 81.5 ms
min 63 ms
max 124 ms
```

This however doesn't include the very first time which is `8492 ms`. Yeah that's longer than 8 seconds. 

So the conclusion is that this too needs to be done on a worker thread. I do realize that more and more things are solved with a worker threads in emulsion. If I'm not mistaken there are currently at most 7 worker threads at any given time, but I believe that's well within the reasonable amount of threads.
