### ISSUE TITLE
Deleting files slowly, then deleting the folder

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/emulsion#166]
As @akimdi wrote at https://github.com/ArturKovacs/emulsion/pull/164#issuecomment-752750084:

It hangs a little for a few seconds when I delete files one by one and there are no files left in the folder and then throws this error

```
Error occurred while loading image: Could not got current file descriptor
Error occurred while loading image: Could not got current file descriptor
Error while updating directory Error(DirError(Other("No such file or directory (os error 2)")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

**Comment by ArturKovacs** [comment]
I do get the "Error occurred while loading image" message but not the last one, and the trashing happens instantly when I do it from emulsion. It would help @akimdi if you could answer the following questions:

1. Which operating system did you encounter this on?
2. What is the version of that operating system?
3. Does trashing take long when you delete the image files from that same folder using your file browser?

**Comment by akimdi** [comment]
I'm using archlinux. Kernel 5.4 LTS.
```uname -a```
```Linux pc 5.4.86-1-lts #1 SMP Wed, 30 Dec 2020 21:01:35 +0000 x86_64 GNU/Linux```
When I delete a photo in any other way the photo is deleted immediately.
I have tried deleting with [nnn](https://github.com/jarun/nnn) [ranger](https://github.com/ranger/ranger) [nemo](https://github.com/linuxmint/nemo) and [gnome nautilus](https://gitlab.gnome.org/GNOME/nautilus). All OK.

When I was testing, I found another bug.
If you delete photos from a folder one by one, and when the last photo is deleted accidentally press the delete key again, then emulsion deletes the folder in which the photos were located.
I recorded a [video](https://youtu.be/OyEQWHbdvbU) so that you can clearly see what I'm talking about.

Sorry for the long answer. New Year's holidays knocked me out of my usual mode of work 🙂️

**Comment by akimdi** [comment]
By the way, I also got the same black screen on the video as [here](https://github.com/ArturKovacs/emulsion/issues/99)

[https://youtu.be/OyEQWHbdvbU?t=344](https://youtu.be/OyEQWHbdvbU?t=344)
