### ISSUE TITLE
Possibly some bugs

### ISSUE THREAD

**Issue by kneasle** [ArturKovacs/emulsion#174]
Firstly, very cool project!  It fits right in with my minimalist Linux setup.  But I have a few questions about things that might be bugs/feature requests.  I'm merging them all into one issue so I don't spam up the issue list.

- There's a typo in the help menu (`Copy Image to the Cipboard`), but I don't know how to fix this - I guess there must be some kind of localisation happening that I don't understand, because I `grep`ped the repo for `Cipboard` and got nothing.
- I'm not sure what's going on with the viewport location when pressing `Q` to reset to 1:1 resolution - in most cases I tried it simply flung the image way off the bottom-right corner of my screen.  Perhaps there is some logic to this, but I would expect zooming to always preserve the point of the image in the centre of the screen.
- Lastly, and least importantly, I'd be nice to have Vi-style keybindings so that I can control Emulsion completely using a keyboard.  This is probably unnecessary, but for me (and plenty of other people) Vim's keybindings are very strong muscle memory.

I'd be happy to make PRs for any of these :grin:.  Thanks again for such a cool program!

**Comment by ArturKovacs** [comment]
> There's a typo in the help menu (Copy Image to the Cipboard), but I don't know how to fix this 

Well spotted, I completely missed this! It's all smoke and mirrors, and it's actually just an image, that's why you didn't find the text. You can find a document called "Emulsion Usage.odt" under "resource_dev/Usage Panel". If you are interested in fixing this, please edit the document using Libre Office. Then you can export the document as a png from File->Export. Set the width to 994 pixels. The resulting image should then overwrite "resource/usage.png".

> I'm not sure what's going on with the viewport location when pressing Q to reset to 1:1 resolution

I created #175

> I'd be nice to have Vi-style keybindings so that I can control Emulsion completely using a keyboard

I believe this can already be done by setting the approproate key bindings (`pan_left`, `pan_right`, etc). See: https://arturkovacs.github.io/emulsion-website/bindings.html

**Comment by kneasle** [comment]
> Well spotted, I completely missed this! It's all smoke and mirrors, and it's actually just an image, that's why you didn't find the text.

Aha! That explains it - I was getting so confused that I almost thought there was bug in `ripgrep` 😅 (which actually would be quite scary given the number of programs which use `regex`).

> I believe this can already be done by setting the approproate key bindings (`pan_left`, `pan_right`, etc)

Oooh! That's cool - I'll do some fiddling when I get back to my computer.

**Comment by ArturKovacs** [comment]
- I fixed the typo in e25e53a7b7fd67d5ddd23a021b8bdf65a06bb5b9.
- The resetting issue is tracked by #175
- The keyboard driven camera controls are implemented as was stated earlier

So I'm closing this, but let me know if I missed something.
