### ISSUE TITLE
Some GIFs don't play their animation

### ISSUE THREAD

**Issue by animeavi** [ArturKovacs/emulsion#190]
I'm not sure what's different about them but here's one example.
![makes u think](https://user-images.githubusercontent.com/14946679/114203841-868b1180-9926-11eb-8593-fc8a67994fa1.gif)

**Comment by ArturKovacs** [comment]
Addressed by 50b248d5d7f3a96ddfbdaab7cd6877c1bd0cc4d3.

On a different note: if this is made by you, I recommend **not** copying the first frame to the end, because then, that frame will appear twice (at the end and then at the beginning again). This makes it look as if the animation pauses for a moment.
