### ISSUE TITLE
Feature: copy current image to clipboard

### ISSUE THREAD

**Issue by CorneliusCornbread** [ArturKovacs/emulsion#79]
Emulsion has literally every feature I need except for one: copy image to clipboard. Having both a keyboard shortcut and a button would be nice

**Comment by ArturKovacs** [comment]
Thank you for the feature request! I really need to figure out a way to add more buttons while keeping the layout organized and minimal. What I'm thihking is that maybe the info button could be replaced with a button that brings up an extra panel with more buttons on it. I made a quick illustration of how I'm imagining it.

![NewButtonsConcept](https://user-images.githubusercontent.com/8320264/81376454-e0c29780-9103-11ea-8f05-aefd4aeff6a2.png)

Later this could be made into a full-width panel with a bunch of buttons and a full-path display once (if) there's gonna be font rendering. This would be super nice for #8.

**Comment by CorneliusCornbread** [comment]
I think a common way to do it is to have three dots (like in chrome or Window's own image viewer) in a corner of the window. Which you click on to bring up a pop up some kind. Not sure how descriptive and intuitive the arrow would be, but I see 3 dots commonly used to indicate a "more" button.

**Comment by ArturKovacs** [comment]
I started working on this. Unfortunately it seems there's no cross-platform crate that allows placing image data onto the clipboard so that's what I making now. I will need help with the macos implementation however.

**Comment by ArturKovacs** [comment]
Okay so after a fairly long process I finally published the clipboard handling crate that can place image data onto the clipboard. It's here: https://crates.io/crates/arboard

Next step is to allow shortcut definitions that use the Command key on mac but the Ctrl key elsewhere. This will allow users to use the well known `Ctrl/Cmd + C` keyboard shortcut to copy the current image.

Handing the pixel data over to the clipboard is surprisingly tricky though, because emulsion Uploads the pixel data to the GPU and then gets rid of the original RAM storage. It is possible to read back pixel data from the GPU but the problem is that once Large Image Support is implemented (#99) a single image may be split up into several textures which would make it quite messy to reconstruct the original pixel array. Instead I think there should be a separate thread that doesn't do anything until it gets a request for uploading a texture from a given path to the clipboard. This way the clipboard interaction would not have to be somehow hacked into the existing image loading and caching architecture and putting it on a separate thread would allow the UI to remain responsive while placing large images to the clipboard.

**Comment by CorneliusCornbread** [comment]
> Okay so after a fairly long process I finally published the clipboard handling crate that can place image data onto the clipboard. It's here: https://crates.io/crates/arboard
> 
> Next step is to allow shortcut definitions that use the Command key on mac but the Ctrl key elsewhere. This will allow users to use the well known `Ctrl/Cmd + C` keyboard shortcut to copy the current image.
> 
> Handing the pixel data over to the clipboard is surprisingly tricky though, because emulsion Uploads the pixel data to the GPU and then gets rid of the original RAM storage. It is possible to read back pixel data from the GPU but the problem is that once Large Image Support is implemented (#99) a single image may be split up into several textures which would make it quite messy to reconstruct the original pixel array. Instead I think there should be a separate thread that doesn't do anything until it gets a request for uploading a texture from a given path to the clipboard. This way the clipboard interaction would not have to be somehow hacked into the existing image loading and caching architecture and putting it on a separate thread would allow the UI to remain responsive while placing large images to the clipboard.

Couldn't you just load it from disk onto the clipboard at that point? Or is there some reason for performance that would make that not possible?

**Comment by ArturKovacs** [comment]
I could but for some files the correct orientation of the image is in a small metadata field, while the pixel data as it comes from the file doesn't  show in the correct orientation. At the same time the idiomatic way to send image data on windows is in a bitmap format which in itself doesn't support specifying the orientation in the header so in this case the pixel array needs to be rotated before placing it onto the clipboard. This might take a second or two for larger images which is why to do this in a parallel thread.

However it is possible to send images in formats other than bitmap on Windows so I need to investigate that, and I'll probably add a `set_image_from_jpeg()` or `set_image_from_encoded()` to `arboard` so that this is easier for everyone.
