### ISSUE TITLE
Feature request: display absolute path

### ISSUE THREAD

**Issue by jatentaki** [ArturKovacs/emulsion#8]
First of all, thanks a lot for creating the app, I've been looking for a lightweight and fast image viewer. Many available solutions try to go ahead with some gallery previews or other bells and whistles which make it unacceptably slow with huge image collections and/or accessing images on remote drives.

I work in computer vision and I find myself comparing images constantly. A typical scenario for me is to have the same set of images processed with two different methods and comparing them visually. So the directory structure would be like

```
source_dir:
  image_1.jpg
  image_2.jpg
  ...

processed_dir_1:
  image_1.jpg
  image_2.jpg
  ...

processed_dir_2:
  image_1.jpg
  image_2.jpg
  ...
```
or, in other words, the filenames are the same but reside in different directories. I will therefore often compare `processed_dir_1/image_1.jpg` with `processed_dir_2/image_2.jpg` and try not to confuse which image is which: both of them just show `image_1.jpg: E M U L S I O N` on the top bar. I wish there was an (opt-in) way to show the full image path.

Thinking out loud, those can get quite long so perhaps a more readable solution would be to show `n` lowest-level subdirectories (so that `emulsion dir/subdir/subsubdir/image_1.jpg --n 1` shows as `subsubdir/image_1.jpg: E M U L S I O N`)? Sorry for the blurriness, I am trying to depict my usecase more than a concrete solution.

**Comment by ArturKovacs** [comment]
I think you explained your usecase well so no blurriness at all.

What makes this a bit difficult right now is that it might be something that other users, who don't wish to use command line arguments, would also be interested in. But I'm actually not so sure about that.

I like your general approach because it solves the problem and it seems to be quire easy to implement. However instead of specifying a command line argument I think a config file attribute would be more appropriate. As currently there is a cfg.toml which is just a text file so it's easy to mess with. What do you think?

**Comment by ArturKovacs** [comment]
Probably the best kind of behaviour would be if this could be set from both the config and the command line. If a command line value is specified then that value is used, ignoring the cfg file.

This should be done after #64.

**Comment by ArturKovacs** [comment]
@Aloso would you be interested in implementing this?

**Comment by Aloso** [comment]
Yes, you can assign me.
