### ISSUE TITLE
Provide a "Fit to screen" mode that does not scale up small images

### ISSUE THREAD

**Issue by Shnatsel** [ArturKovacs/emulsion#88]
When scrolling through a folder with images of different sizes I find myself switching between "Fit to screen" and "Original size" view modes often: smaller images look bad when blown up to the entire screen and are better viewed in their original size, but after I switch to the original size and encounter an image larger than my screen I have to switch back to "Fit to screen" mode to see them. This quickly becomes tedious.

FWIW most other viewers seem to default to showing the image at the original size if it's smaller than the screen, but fit larger images to screen.

**Comment by Shnatsel** [comment]
Actually, now that I look closely, I don't see an "Always fit to screen" mode in other viewers, at least not as a GUI control. In the spirit of keeping the number of buttons to a minimum (see #80) perhaps the mode that blows up smaller images should be keybinding-only.

**Comment by ArturKovacs** [comment]
I think a third mode would significantly complicate things. I think it's mutch easier to just switch to the "other mode" if what you see is not what you want. Opposed to this keeping 3 modes in mind and maybe having to cycle through them to find the one you need decreases the usablility.

But I understand your frustration. I'm thinking that there could be a modifier that affects how the "fit to screen" mode behaves. This could be set as a configuration option something like
```
img_fit_stretch = false
```

**Comment by Shnatsel** [comment]
I do think the default "fit to screen" should not enlarge images. However, I could see myself reaching for the other one as well if I wanted to make the image larger but didn't want to bother with placing mouse exactly at the center so that the image would remain centered. So I don't think a static config is the way to go. I suppose mapping zoom in/out actions to `+` and `-` buttons and making those always zoom to the center, ignoring mouse position, would invalidate the use cases for "fit to screen with blowup" mode.

**Comment by ArturKovacs** [comment]
> I do think the default "fit to screen" should not enlarge images. 

In that case there has to be some easy way to set the default behaviour because I prefer it stretching images to fill the window. For example emulsion could remember the last mode used before the window was closed and next time it could start with that.

With all things considered it seems that the most reasonable approach is to have three separate modes (even though I would love to be proven wrong). We obviously need to introduce a new keybinding but the question remaining is if we need to change the default binding for the `F` key. This depends on how many popular image viewers use the `F` key for "fit only if larger". The windows Photos app doesn't do that neither does Irfanview (which is/was another popular program), neither does the macOS photos app from what I could find.
