### ISSUE TITLE
[Bug] Certain images wont open in Emulsion

### ISSUE THREAD

**Issue by TandersT** [ArturKovacs/emulsion#97]
I have a series of images, where 6 of them wont open in Emulsion. They are PNG files and there doesn't seem to be anything particularly wrong with them. 

In emulsion, it displays "[none]" in the header when I open them, and nothing is displayed in the viewer.

The zip file containts one of the non-working images (filter-6.png) and a working one (filter-7.png)

I'm running win10.

[Filters.zip](https://github.com/ArturKovacs/emulsion/files/4763275/Filters.zip)

**Comment by Aloso** [comment]
The file `filter-6.png` is in fact a JPEG file, not a PNG. If you rename it to `filter-6.jpg`, it works correctly in emulsion.

I guess that other image viewers detect the file type without relying on the file ending.

**Comment by ArturKovacs** [comment]
This is because the image content is jpg, but the extension is png. This is a bug nevertheless so I'll get to it.

**Comment by ArturKovacs** [comment]
@Aloso if you'd be interested in tackling this, you are more than welcome to, just let me know :)

**Comment by Aloso** [comment]
I'll see if I can fix it. The problem appears to be the `load_image` function in `image_loader`, which calls [`image::open`](https://docs.rs/image/0.23.5/image/fn.open.html). Instead, we should call [`image::load`](https://docs.rs/image/0.23.5/image/fn.load.html) and determine the image format with [`image::guess_format`](https://docs.rs/image/0.23.5/image/fn.guess_format.html).

**Comment by ArturKovacs** [comment]
That right!

Note that format guessing already happens as shown below. Currently it's only being used to determine if an image is a gif. (Don't ask me why I didn't use that for all images :D) Instead of immediately matching the enum you could keep the enum and maybe pass it onto our `load_image` function. Note that format guessing can fail in which case we should fall back to the good ol' filename extension (which is how `image::open` determines the format, as you know).

https://github.com/ArturKovacs/emulsion/blob/a041edbb32e222f6f49f5eaefe9b7cba4bfb993c/src/image_cache/image_loader.rs#L176-L182
